# Generated by Django 6.0.1 on 2026-01-29 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Recipe Title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', unique=True)),
                ('author', models.CharField(help_text='Your First and Last Names', max_length=200)),
                ('mealtype', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Sides', 'Sides, Dips, and Appetizers'), ('Entree', 'Entree'), ('Dessert', 'Dessert')], default='Entree', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('recipe_ingredients', models.TextField(blank=True, help_text='Enter key ingredients on separate lines', null=True)),
                ('recipe_instructions', models.TextField(blank=True, help_text='Step-by-step cooking instructions', null=True)),
                ('recipe_short_card_description', models.TextField(blank=True, help_text='Short description for cards', null=True)),
                ('description_blurb_1', models.TextField(blank=True, help_text='1st Description')),
                ('recipe_image_1', models.ImageField(blank=True, upload_to='recipe_photos/')),
                ('description_blurb_2', models.TextField(blank=True, help_text='2nd Description')),
                ('recipe_image_2', models.ImageField(blank=True, upload_to='recipe_photos/')),
                ('description_blurb_3', models.TextField(blank=True, help_text='3rd Description')),
                ('recipe_image_3', models.ImageField(blank=True, upload_to='recipe_photos/')),
                ('description_blurb_4', models.TextField(blank=True, help_text='4th Description')),
                ('recipe_image_4', models.ImageField(blank=True, upload_to='recipe_photos/')),
                ('description_blurb_5', models.TextField(blank=True, help_text='5th Description')),
                ('recipe_image_5', models.ImageField(blank=True, upload_to='recipe_photos/')),
                ('recipe_video', models.URLField(blank=True, help_text='Optional YouTube Video', null=True)),
            ],
            options={
                'verbose_name': 'Recipe Article',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='SensibleSuppers.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='SensibleSuppers.recipearticle')),
            ],
        ),
    ]
